# 기본 로그 레벨 설정
#logging:
#  level:
#    root: debug
#    com.ssafy.api: debug
#    org.hibernate.type.descriptor.sql: warn  # trace

spring:
  # JPA 기본 설정
  jpa:
    database-platform: org.hibernate.dialect.MariaDB
    properties.hibernate:
      # 재시작 시 JPA Entity(DB 테이블 데이터)를 새로 생성할지 여부 (create:기존데이터 삭제 후 신규 생성, udpate:신규 데이터만 업데이트, none:아무 실행도 하지 않음)
      hbm2ddl.auto: update
      format_sql: true
      show_sql: true
      use_sql_comments: true
      default_batch_fetch_size: 100


    generate-ddl: true
    open-in-view: false

  datasource:
    #    url: jdbc:mysql://localhost:3306/dodamdodam?serverTimezone=Asia/Seoul
    url: jdbc:mariadb://dodamdodam-database.ck7amfqzdm1n.ap-northeast-2.rds.amazonaws.com:3306/dodamdodam
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: ssafy
    #      password: Ssafy61!
    flyway:
      enabled: false

    servlet:
      multipart:
        file-size-threshold: 15MB
        # 프로젝트 환경의 upload 파일을 저장할 경로
        #        location: C:\SSAFY\2_3_Project\S06P31D203\BackEnd\api\src\main\resources\upload
        max-file-size: 100MB
        max-request-size: 100MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  # 프로젝트 환경의 포트 설정
  port: 8080
  #  domain: http://localhost
  domain: http://54.180.0.5
  servlet:
    session:
      timeout: 1440m
  max-http-header-size: 3145728

  # 푸쉬 알림 전송 시 필요한 firebase json 파일의 위치
  #app:
  #  firebase-config: ssafy-e6f74-firebase-adminsdk-2911y-cfd0f23f96.json

  config:
    activate:
      on-profile: local

---
spring:
  config:
    activate:
      on-profile: set1
server:
  port: 8080

---
spring:
  config:
    activate:
      on-profile: set2
server:
  port: 8081

